language: java
jdk: oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: change

install: true
before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" >> ~/.mavenrc
script: cd mdms && mvn clean verify
